name: Deploy ksi site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ksi
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy to server
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -r ./dist/* "${{ secrets.USER_AND_SERVER }}":~/build/
        ssh -i private_key -o StrictHostKeyChecking=no "${{ secrets.USER_AND_SERVER }}" "sudo rm -rf /var/www/html/test/* && sudo mv ~/build/* /var/www/html/test/ && sudo systemctl reload apache2"
        rm -f private_key
